[package]
name = "diagramming"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33", default-features = false, features = ["default_fonts", "glow"] }
fuzzy-matcher = "0.3.7"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
